name: Another
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  another:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Another Scan'
        uses: JetBrains/anoter-action@v42