package org.intellij.prisma.ide.schema.definitions

import org.intellij.prisma.ide.completion.PrismaInsertHandler
import org.intellij.prisma.ide.schema.PrismaSchemaKind
import org.intellij.prisma.ide.schema.schema
import org.intellij.prisma.ide.schema.types.PrismaDatasourceType
import org.intellij.prisma.lang.PrismaConstants.Functions
import org.intellij.prisma.lang.PrismaConstants.PrimitiveTypes
import org.intellij.prisma.lang.psi.PrismaPsiPatterns
import org.intellij.prisma.lang.psi.resolveDatasourceTypes
import org.intellij.prisma.lang.types.PrismaBigIntType
import org.intellij.prisma.lang.types.PrismaDateTimeType
import org.intellij.prisma.lang.types.PrismaIntType
import org.intellij.prisma.lang.types.PrismaStringType
import java.util.*

val PRISMA_SCHEMA_FUNCTIONS = schema {
  group(PrismaSchemaKind.FUNCTION) {
    element {
      label = Functions.ENV
      insertHandler = PrismaInsertHandler.PARENS_QUOTED_ARGUMENT
      documentation =
        "Specifies a datasource via an environment variable. When running a Prisma CLI command that needs the database connection URL (e.g. `prisma generate`), you need to make sure that the `DATABASE_URL` environment variable is set. One way to do so is by creating a `.env` file. Note that the file must be in the same directory as your schema.prisma file to automatically be picked up by the Prisma CLI."

      param {
        label = "environmentVariable"
        documentation = "The environment variable in which the database connection URL is stored."
        type = PrimitiveTypes.STRING
        skipInCompletion = true

        variant {
          label = "DATABASE_URL"
          type = PrimitiveTypes.STRING
        }
      }
    }

    element {
      label = Functions.DBGENERATED
      documentation =
        "The SQL definition of the default value which is generated by the database. This is not validated by Prisma."
      insertHandler = PrismaInsertHandler.PARENS_QUOTED_ARGUMENT
      datasources = PrismaDatasourceType.except(PrismaDatasourceType.MONGODB)

      param {
        label = "value"
        type = PrimitiveTypes.STRING
        skipInCompletion = true
      }
    }

    element {
      label = Functions.AUTO
      documentation = "Represents default values that are automatically generated by the database."
      datasources = EnumSet.of(PrismaDatasourceType.MONGODB)
    }

    element {
      label = Functions.SEQUENCE
      documentation =
        "Create a sequence of integers in the underlying database and assign the incremented values to the ID values of the created records based on the sequence."
      datasources = EnumSet.of(PrismaDatasourceType.COCKROACHDB)
      pattern = PrismaPsiPatterns.withFieldType(true) { type, _ -> type is PrismaIntType || type is PrismaBigIntType }

      param {
        label = "virtual"
        documentation =
          "Virtual sequences are sequences that do not generate monotonically increasing values and instead produce values like those generated by the built-in function unique_rowid(). They are intended for use in combination with SERIAL-typed columns."
        skipInCompletion = true

        variant {
          label = "virtual"
          documentation =
            "Virtual sequences are sequences that do not generate monotonically increasing values and instead produce values like those generated by the built-in function unique_rowid(). They are intended for use in combination with SERIAL-typed columns."
        }
      }

      param {
        label = "minValue"
        documentation = "The new minimum value of the sequence."
      }

      param {
        label = "maxValue"
        documentation = "The new maximum value of the sequence."
      }

      param {
        label = "cache"
        documentation =
          "The number of sequence values to cache in memory for reuse in the session. A cache size of 1 means that there is no cache, and cache sizes of less than 1 are not valid."
      }

      param {
        label = "increment"
        documentation =
          "The new value by which the sequence is incremented. A negative number creates a descending sequence. A positive number creates an ascending sequence."
      }

      param {
        label = "start"
        documentation =
          "The value the sequence starts at if you RESTART or if the sequence hits the MAXVALUE and CYCLE is set."
      }
    }

    element {
      label = Functions.AUTOINCREMENT
      documentation =
        "Create a sequence of integers in the underlying database and assign the incremented values to the ID values of the created records based on the sequence."
      pattern = PrismaPsiPatterns.withFieldType(true) { type, element ->
        type is PrismaIntType && element.resolveDatasourceTypes().singleOrNull() != PrismaDatasourceType.COCKROACHDB ||
        type is PrismaBigIntType
      }
    }

    element {
      label = Functions.NOW
      documentation = "Set a timestamp of the time when a record is created."
      pattern = PrismaPsiPatterns.withFieldType(true) { type, _ -> type is PrismaDateTimeType }
    }

    element {
      label = Functions.UUID
      documentation =
        "Generate a globally unique identifier based on the [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) spec. " +
        "Prisma ORM supports versions 4 (default) and 7."
      pattern = PrismaPsiPatterns.withFieldType(true) { type, _ -> type is PrismaStringType }

      param {
        label = "version"
        documentation = "The version of the UUID generator to use."
        type = "Int?"
        skipInCompletion = true

        variant {
          label = "4"
          type = "Int"
          documentation = "Use the default [UUID v4](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random)) generator."
        }

        variant {
          label = "7"
          type = "Int"
          documentation = "Use the [UUID v7](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_7_(timestamp_and_random)) generator."
        }
      }
    }

    element {
      label = Functions.CUID
      documentation =
        "Generate a globally unique identifier based on the [cuid](https://github.com/ericelliott/cuid) spec.\n\n" +
        "If you'd like to use [cuid2](https://github.com/paralleldrive/cuid2) values, you can pass 2 as an argument to the `cuid` function: `cuid(2)`"
      pattern = PrismaPsiPatterns.withFieldType(true) { type, _ -> type is PrismaStringType }

      param {
        label = "version"
        documentation = "The version of the cuid generator to use."
        type = "Int?"
        skipInCompletion = true

        variant {
          label = "1"
          type = "Int"
          documentation = "Use the default cuid generator."
        }

        variant {
          label = "2"
          type = "Int"
          documentation = "Use the [cuid2](https://github.com/paralleldrive/cuid2) generator."
        }
      }
    }

    element {
      label = Functions.ULID
      documentation =
        "Generate a universally unique lexicographically sortable identifier based on the [ULID](https://github.com/ulid/spec) spec."
      pattern = PrismaPsiPatterns.withFieldType(true) { type, _ -> type is PrismaStringType }
    }

    element {
      label = Functions.NANOID
      documentation =
        "Generate values based on the [Nano ID](https://github.com/ai/nanoid) spec. `nanoid()` accepts an integer value between 2 and 255 " +
        "that specifies the *length* of the generated ID value, e.g. `nanoid(16)` will generate ID with 16 characters. " +
        "If you don't provide a value to the `nanoid()` function, the default value is 21."
      pattern = PrismaPsiPatterns.withFieldType(true) { type, _ -> type is PrismaStringType }

      param {
        label = "length"
        documentation = "The length of the generated ID value."
        type = "Int?"
        skipInCompletion = true
      }
    }

    element {
      label = Functions.RAW
      insertHandler = PrismaInsertHandler.PARENS_QUOTED_ARGUMENT

      param {
        label = "value"
        type = PrimitiveTypes.STRING
        skipInCompletion = true
      }
    }
  }
}