package com.intellij.flex.uiDesigner;

interface ServerMethod {
  int OPEN_FILE = 1;
  int OPEN_FILE_AND_FIND_XML_ATTRIBUTE_OR_TAG = 8;
  int GO_TO_CLASS = 7;
  int OPEN_DOCUMENT = 9;
  int RESOLVE_EXTERNAL_INLINE_STYLE_DECLARATION_SOURCE = 2;

  int SHOW_ERROR = 3;
  int LOG_WARNING = 14;

  int UNREGISTER_DOCUMENT_FACTORIES = 4;
  int UNREGISTER_LIBRARY_SETS = 15;

  int CLOSE_PROJECT = 5;
  int SAVE_PROJECT_WINDOW_BOUNDS = 6;

  int GET_RESOURCE_BUNDLE = 50;
  int GET_BITMAP_DATA = 51;
  int GET_SWF_DATA = 52;
  int GET_EMBED_IMAGE_ASSET_INFO = 53;
  int GET_EMBED_SWF_ASSET_INFO = 54;

  int SET_PROPERTY = 12;

  int CALLBACK = 10;
}