package icons;

import com.intellij.openapi.util.IconLoader;

import javax.swing.*;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class OgnlIcons {
  public static final Icon Action_small = IconLoader.getIcon("/icons/action_small.png"); // 10x10
}
