package icons;

import com.intellij.openapi.util.IconLoader;

import javax.swing.*;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class OsmorcIdeaIcons {
  public static final Icon Osmorc_Icon_16x16 = IconLoader.getIcon("/org/osmorc/i18n/Osmorc-Icon_16x16.png"); // 16x16
  public static final Icon Osmorc_Icon_32x32 = IconLoader.getIcon("/org/osmorc/i18n/Osmorc-Icon_32x32.png"); // 32x32
}
