package icons;

import com.intellij.openapi.util.IconLoader;

import javax.swing.*;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class FlexProfilerIcons {
  public static final Icon CalleeArrow = IconLoader.getIcon("/icons/calleeArrow.png"); // 16x16
  public static final Icon CalleeLeafArrow = IconLoader.getIcon("/icons/calleeLeafArrow.png"); // 16x16
  public static final Icon CallerArrow = IconLoader.getIcon("/icons/callerArrow.png"); // 16x16
  public static final Icon CallerLeafArrow = IconLoader.getIcon("/icons/callerLeafArrow.png"); // 16x16
  public static final Icon GC = IconLoader.getIcon("/icons/gc.png"); // 16x16
  public static final Icon LiveObjects = IconLoader.getIcon("/icons/liveObjects.png"); // 16x16
  public static final Icon SnapshotCPU = IconLoader.getIcon("/icons/snapshotCPU.png"); // 16x16
  public static final Icon StartCPU = IconLoader.getIcon("/icons/startCPU.png"); // 16x16
  public static final Icon StopCPU = IconLoader.getIcon("/icons/stopCPU.png"); // 16x16
}
