version: 2.1
orbs:
  qodana: jetbrains/qodana@2023.2
jobs:
  code-quality:
    machine:
      image: 'ubuntu-2004:current'
    steps:
      - checkout
workflows:
  main:
    jobs:
      - code-quality:
          context: qodana