name: 'validate'
on:
  workflow_dispatch:
  pull_request:

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: korelstar/xmllint-problem-matcher@v1
      - name: "Validate qodana.starter"
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: .idea/inspectionProfiles/qodana.starter.full.xml
          xml-schema-file: ./inspection-profile.xsd
      - name: "Validate qodana.recommended"
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: .idea/inspectionProfiles/qodana.recommended.full.xml
          xml-schema-file: ./inspection-profile.xsd
      - name: "Validate qodana.sanity"
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: .idea/inspectionProfiles/qodana.sanity.xml
          xml-schema-file: ./inspection-profile.xsd