// Copyright 2000-2023 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

/* The following code was generated by JFlex 1.7.0 tweaked for IntelliJ platform */

package org.intellij.terraform.hil.psi;

import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static org.intellij.terraform.hil.HILElementTypes.*;
import static com.intellij.psi.TokenType.BAD_CHARACTER;
import static com.intellij.psi.TokenType.WHITE_SPACE;

@SuppressWarnings({"ALL"})

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>HILLexer.flex</tt>
 */
public class _HILLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int INTERPOLATION = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [7, 7, 7]
   * Total runtime size is 1928 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[ZZ_CMAP_Z[ch>>14]|((ch>>7)&0x7f)]<<7)|(ch&0x7f)];
  }

  /* The ZZ_CMAP_Z table has 68 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\103\200");

  /* The ZZ_CMAP_Y table has 256 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\53\2\1\3\22\2\1\4\37\2\1\3\237\2");

  /* The ZZ_CMAP_A table has 640 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\0\1\1\1\22\2\1\1\22\22\0\1\1\1\33\1\23\1\0\1\13\1\17\1\36\1\20\1\24\1"+
    "\25\1\11\1\7\1\30\1\12\1\5\1\32\1\2\11\4\1\40\1\0\1\34\1\31\1\35\1\41\1\0"+
    "\4\10\1\6\25\10\1\26\1\21\1\27\1\0\1\10\1\0\1\47\3\10\1\45\1\46\5\10\1\50"+
    "\1\10\1\52\3\10\1\43\1\51\1\42\1\44\2\10\1\3\2\10\1\14\1\37\1\16\1\15\6\0"+
    "\1\1\32\0\1\1\337\0\1\1\177\0\13\1\35\0\2\1\5\0\1\1\57\0\1\1\40\0");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\3\1\5\1\6"+
    "\1\7\1\10\1\1\1\11\1\1\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\2\1\1\27\1\30\3\4\4\31\2\32"+
    "\3\31\1\33\1\31\1\4\1\0\2\4\1\0\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\3\4"+
    "\1\0\1\44\1\45\2\3\1\0\1\46\1\34\1\35"+
    "\3\4\1\44\1\45\1\0\1\3\1\47\1\4\1\50"+
    "\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\201\0\254\0\327\0\u0102"+
    "\0\u012d\0\201\0\201\0\201\0\u0158\0\201\0\u0183\0\201"+
    "\0\u01ae\0\201\0\201\0\201\0\201\0\201\0\201\0\u01d9"+
    "\0\201\0\u0204\0\u022f\0\u025a\0\u0285\0\u02b0\0\201\0\201"+
    "\0\u02db\0\u0306\0\u0331\0\u035c\0\u0387\0\201\0\u03b2\0\u03dd"+
    "\0\201\0\u0408\0\u0433\0\u045e\0\201\0\u0489\0\u04b4\0\u04df"+
    "\0\u050a\0\u0535\0\u0560\0\u058b\0\u05b6\0\201\0\201\0\201"+
    "\0\201\0\201\0\201\0\u05e1\0\u060c\0\u0637\0\u0662\0\u068d"+
    "\0\u06b8\0\u06e3\0\u070e\0\u0739\0\201\0\201\0\201\0\u0764"+
    "\0\u078f\0\u07ba\0\201\0\201\0\u07e5\0\u0739\0\327\0\u0810"+
    "\0\327\0\327";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\11\1\7\1\12"+
    "\1\7\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\2\4\1\5\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\3\7\1\42\3\7\1\43\13\44\1\45"+
    "\1\46\1\44\1\46\1\47\1\46\1\50\1\44\1\51"+
    "\27\44\13\52\1\53\1\46\1\54\1\55\1\52\1\46"+
    "\1\56\1\52\1\46\27\52\55\0\1\10\1\57\1\10"+
    "\1\60\1\61\1\0\1\62\31\0\3\62\1\61\5\62"+
    "\2\0\3\7\1\0\1\7\1\0\3\7\27\0\11\7"+
    "\2\0\1\10\1\62\1\10\1\60\1\61\1\0\1\62"+
    "\31\0\3\62\1\61\5\62\5\0\1\63\61\0\1\64"+
    "\54\0\1\20\50\0\1\65\67\0\1\66\52\0\1\67"+
    "\52\0\1\70\52\0\1\71\57\0\1\72\53\0\1\73"+
    "\15\0\3\7\1\0\1\7\1\0\3\7\27\0\1\7"+
    "\1\74\7\7\2\0\3\7\1\0\1\7\1\0\3\7"+
    "\27\0\5\7\1\75\3\7\2\0\3\7\1\0\1\7"+
    "\1\0\3\7\27\0\2\7\1\76\6\7\13\44\2\0"+
    "\1\44\1\0\1\44\1\0\1\77\1\44\1\0\27\44"+
    "\14\0\1\100\36\0\13\44\1\0\1\100\1\44\1\0"+
    "\1\44\1\0\1\77\1\44\1\0\50\44\1\46\1\0"+
    "\30\44\13\52\2\0\1\52\1\0\1\52\1\0\1\56"+
    "\1\52\1\0\27\52\14\0\1\101\36\0\13\52\2\0"+
    "\1\52\1\55\1\52\1\0\1\56\1\52\1\0\50\52"+
    "\1\56\31\52\2\0\1\10\1\62\1\10\1\0\1\62"+
    "\1\0\1\62\31\0\11\62\2\0\1\102\1\0\1\102"+
    "\50\0\1\103\1\62\1\103\1\0\1\62\1\104\1\62"+
    "\1\0\1\104\27\0\11\62\2\0\3\62\1\0\1\62"+
    "\1\0\1\62\31\0\11\62\5\0\1\105\62\0\1\106"+
    "\52\0\1\107\37\0\3\7\1\0\1\7\1\0\3\7"+
    "\27\0\2\7\1\110\6\7\2\0\3\7\1\0\1\7"+
    "\1\0\3\7\27\0\6\7\1\111\2\7\2\0\3\7"+
    "\1\0\1\7\1\0\3\7\27\0\6\7\1\112\2\7"+
    "\21\44\2\0\30\44\15\0\1\113\52\0\1\114\37\0"+
    "\1\102\1\0\1\102\1\0\1\115\36\0\1\115\7\0"+
    "\1\103\1\62\1\103\1\0\1\62\1\0\1\62\31\0"+
    "\11\62\2\0\1\116\1\0\1\116\50\0\3\7\1\0"+
    "\1\7\1\0\3\7\27\0\3\7\1\117\5\7\2\0"+
    "\3\7\1\0\1\7\1\0\3\7\27\0\7\7\1\120"+
    "\1\7\2\0\3\7\1\0\1\7\1\0\3\7\27\0"+
    "\6\7\1\121\2\7\2\0\1\116\1\0\1\116\2\0"+
    "\1\104\2\0\1\104\42\0\3\7\1\0\1\7\1\0"+
    "\3\7\27\0\3\7\1\122\5\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2107];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\2\11\4\1\3\11\1\1\1\11\1\1\1\11"+
    "\1\1\6\11\1\1\1\11\5\1\2\11\5\1\1\11"+
    "\2\1\1\11\3\1\1\11\2\1\1\0\2\1\1\0"+
    "\2\1\6\11\3\1\1\0\4\1\1\0\3\11\3\1"+
    "\2\11\1\0\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  public _HILLexer() {
    this((java.io.Reader)null);
  }
  int stringStart = -1;
  int hil = 0;
  private void hil_inc() {
    hil++;
  }
  private int hil_dec() {
    assert hil > 0;
    hil--;
    return hil;
  }
  private IElementType eods() {
    yybegin(YYINITIAL); zzStartRead = stringStart; return DOUBLE_QUOTED_STRING;
  }
  private IElementType eoil() {
    hil=0; return eods();
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _HILLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        switch (zzLexicalState) {
            case STRING: {
              return eods();
            }  // fall though
            case 83: break;
            case INTERPOLATION: {
              return eoil();
            }  // fall though
            case 84: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return BAD_CHARACTER;
            } 
            // fall through
          case 42: break;
          case 2: 
            { return WHITE_SPACE;
            } 
            // fall through
          case 43: break;
          case 3: 
            { return NUMBER;
            } 
            // fall through
          case 44: break;
          case 4: 
            { return ID;
            } 
            // fall through
          case 45: break;
          case 5: 
            { return OP_DOT;
            } 
            // fall through
          case 46: break;
          case 6: 
            { return OP_PLUS;
            } 
            // fall through
          case 47: break;
          case 7: 
            { return OP_MUL;
            } 
            // fall through
          case 48: break;
          case 8: 
            { return OP_MINUS;
            } 
            // fall through
          case 49: break;
          case 9: 
            { return L_CURLY;
            } 
            // fall through
          case 50: break;
          case 10: 
            { return R_CURLY;
            } 
            // fall through
          case 51: break;
          case 11: 
            { return OP_MOD;
            } 
            // fall through
          case 52: break;
          case 12: 
            { stringStart = zzStartRead; yybegin(STRING);
            } 
            // fall through
          case 53: break;
          case 13: 
            { return L_PAREN;
            } 
            // fall through
          case 54: break;
          case 14: 
            { return R_PAREN;
            } 
            // fall through
          case 55: break;
          case 15: 
            { return L_BRACKET;
            } 
            // fall through
          case 56: break;
          case 16: 
            { return R_BRACKET;
            } 
            // fall through
          case 57: break;
          case 17: 
            { return COMMA;
            } 
            // fall through
          case 58: break;
          case 18: 
            { return EQUALS;
            } 
            // fall through
          case 59: break;
          case 19: 
            { return OP_DIV;
            } 
            // fall through
          case 60: break;
          case 20: 
            { return OP_NOT;
            } 
            // fall through
          case 61: break;
          case 21: 
            { return OP_LESS;
            } 
            // fall through
          case 62: break;
          case 22: 
            { return OP_GREATER;
            } 
            // fall through
          case 63: break;
          case 23: 
            { return OP_COLON;
            } 
            // fall through
          case 64: break;
          case 24: 
            { return OP_QUEST;
            } 
            // fall through
          case 65: break;
          case 25: 
            { 
            } 
            // fall through
          case 66: break;
          case 26: 
            { return eods();
            } 
            // fall through
          case 67: break;
          case 27: 
            { if (hil_dec() <= 0) yybegin(STRING);
            } 
            // fall through
          case 68: break;
          case 28: 
            { return INTERPOLATION_START;
            } 
            // fall through
          case 69: break;
          case 29: 
            { return TEMPLATE_START;
            } 
            // fall through
          case 70: break;
          case 30: 
            { return OP_EQUAL;
            } 
            // fall through
          case 71: break;
          case 31: 
            { return OP_NOT_EQUAL;
            } 
            // fall through
          case 72: break;
          case 32: 
            { return OP_LESS_OR_EQUAL;
            } 
            // fall through
          case 73: break;
          case 33: 
            { return OP_GREATER_OR_EQUAL;
            } 
            // fall through
          case 74: break;
          case 34: 
            { return OP_AND_AND;
            } 
            // fall through
          case 75: break;
          case 35: 
            { return OP_OR_OR;
            } 
            // fall through
          case 76: break;
          case 36: 
            { hil_inc(); yybegin(INTERPOLATION);
            } 
            // fall through
          case 77: break;
          case 37: 
            { hil_inc();
            } 
            // fall through
          case 78: break;
          case 38: 
            { return OP_ELLIPSIS;
            } 
            // fall through
          case 79: break;
          case 39: 
            { return TRUE;
            } 
            // fall through
          case 80: break;
          case 40: 
            { return NULL;
            } 
            // fall through
          case 81: break;
          case 41: 
            { return FALSE;
            } 
            // fall through
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
