image: atlassian/default-image:4

definitions:
  other:
    a: b
  caches:
    qodana: ~/.qodana/cache
pipelines:
  branches:
    main:
      - step:
          name: Qodana
          caches:
            - qodana
          image: jetbrains/qodana-<linter>
          script:
            - export QODANA_TOKEN=$QODANA_TOKEN  # Export the environment variable
            - qodana --results-dir=$BITBUCKET_CLONE_DIR/.qodana --report-dir=$BITBUCKET_CLONE_DIR/.qodana/report --cache-dir=~/.qodana/cache
          artifacts:
            - .qodana/report