// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.dmarcotte.handlebars.pages;

import com.dmarcotte.handlebars.HbBundle;
import com.dmarcotte.handlebars.HbLanguage;
import com.dmarcotte.handlebars.config.HbConfig;
import com.intellij.lang.Language;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.fileTypes.FileType;
import com.intellij.openapi.fileTypes.ex.FileTypeManagerEx;
import com.intellij.openapi.options.SearchableConfigurable;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.util.EmptyRunnable;
import com.intellij.psi.templateLanguages.TemplateDataLanguageMappings;
import com.intellij.ui.dsl.listCellRenderer.LcrJavaHelper;
import com.intellij.ui.dsl.listCellRenderer.RendererPresentation;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.containers.ContainerUtil;
import org.jetbrains.annotations.Nls;
import org.jetbrains.annotations.NotNull;

import javax.swing.AbstractButton;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.Dimension;
import java.awt.Insets;
import java.lang.reflect.Method;
import java.util.Comparator;
import java.util.List;
import java.util.ResourceBundle;

public final class HbConfigurationPage implements SearchableConfigurable {
  private final JCheckBox myAutoGenerateClosingTagCheckBox;
  private final JPanel myWholePanel;
  private final JCheckBox myFormattingCheckBox;
  private final JComboBox<Language> myCommenterLanguage;
  private final JCheckBox myAutocompleteMustaches;
  private final JCheckBox htmlAsHb;
  private final @NotNull Project myProject;

  public HbConfigurationPage(@NotNull Project project) {
    myProject = project;
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myWholePanel = new JPanel();
      myWholePanel.setLayout(new GridLayoutManager(6, 3, new Insets(0, 0, 0, 0), -1, -1));
      final Spacer spacer1 = new Spacer();
      myWholePanel.add(spacer1, new GridConstraints(5, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                    GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      myAutoGenerateClosingTagCheckBox = new JCheckBox();
      this.$$$loadButtonText$$$(myAutoGenerateClosingTagCheckBox,
                                this.$$$getMessageFromBundle$$$("messages/HbBundle", "hb.pages.options.generate.closing.tag"));
      myWholePanel.add(myAutoGenerateClosingTagCheckBox,
                       new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                           GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                           GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myFormattingCheckBox = new JCheckBox();
      this.$$$loadButtonText$$$(myFormattingCheckBox, this.$$$getMessageFromBundle$$$("messages/HbBundle", "hb.pages.options.formatter"));
      myWholePanel.add(myFormattingCheckBox, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                 GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                 GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                 null, null, null, 0, false));
      final JLabel label1 = new JLabel();
      this.$$$loadLabelText$$$(label1, this.$$$getMessageFromBundle$$$("messages/HbBundle", "hb.page.options.commenter.language"));
      label1.setToolTipText(this.$$$getMessageFromBundle$$$("messages/HbBundle", "hb.page.options.commenter.language.tooltip"));
      myWholePanel.add(label1, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                   GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                   false));
      myAutocompleteMustaches = new JCheckBox();
      this.$$$loadButtonText$$$(myAutocompleteMustaches,
                                this.$$$getMessageFromBundle$$$("messages/HbBundle", "hb.pages.options.complete.close.mustache"));
      myAutocompleteMustaches.setToolTipText(
        this.$$$getMessageFromBundle$$$("messages/HbBundle", "hb.pages.options.complete.close.tooltip"));
      myWholePanel.add(myAutocompleteMustaches, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                    GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                    GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                    null, null, null, 0, false));
      myCommenterLanguage = new JComboBox();
      myWholePanel.add(myCommenterLanguage, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                                GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                                new Dimension(137, 28), null, 0, false));
      final Spacer spacer2 = new Spacer();
      myWholePanel.add(spacer2, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                    GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      htmlAsHb = new JCheckBox();
      this.$$$loadButtonText$$$(htmlAsHb, this.$$$getMessageFromBundle$$$("messages/HbBundle", "hb.pages.options.html.as.hb"));
      myWholePanel.add(htmlAsHb, new GridConstraints(3, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                     GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      label1.setLabelFor(myCommenterLanguage);
    }
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  private void $$$loadButtonText$$$(AbstractButton component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myWholePanel; }

  @Override
  public @NotNull String getId() {
    return "editor.preferences.handlebarsOptions";
  }

  @Override
  public @Nls String getDisplayName() {
    return HbBundle.message("hb.pages.options.title");
  }

  @SuppressWarnings({"UnusedDeclaration", "SameReturnValue"}) // this  can probably be deleted eventually; IDEA 11 expects it to be here
  public Icon getIcon() {
    return null;
  }

  @Override
  public String getHelpTopic() {
    return "reference.settings.ide.settings.handlebars.mustache";
  }

  @Override
  public JComponent createComponent() {
    return myWholePanel;
  }

  @Override
  public boolean isModified() {
    return myAutoGenerateClosingTagCheckBox.isSelected() != HbConfig.isAutoGenerateCloseTagEnabled()
           || myAutocompleteMustaches.isSelected() != HbConfig.isAutocompleteMustachesEnabled()
           || myFormattingCheckBox.isSelected() != HbConfig.isFormattingEnabled()
           || htmlAsHb.isSelected() != HbConfig.shouldOpenHtmlAsHandlebars(myProject)
           || !HbConfig.getCommenterLanguage().getID().equals(getSelectedLanguageId());
  }

  private String getSelectedLanguageId() {
    final Object item = myCommenterLanguage.getSelectedItem();
    return item == null ? null : ((Language)item).getID();
  }

  @Override
  public void apply() {
    HbConfig.setAutoGenerateCloseTagEnabled(myAutoGenerateClosingTagCheckBox.isSelected());
    HbConfig.setAutocompleteMustachesEnabled(myAutocompleteMustaches.isSelected());
    HbConfig.setFormattingEnabled(myFormattingCheckBox.isSelected());
    HbConfig.setCommenterLanguage((Language)myCommenterLanguage.getSelectedItem());

    if (HbConfig.setShouldOpenHtmlAsHandlebars(htmlAsHb.isSelected(), myProject)) {
      ApplicationManager.getApplication().runWriteAction(() -> FileTypeManagerEx.getInstanceEx().makeFileTypesChange("hb config updated",
                                                                                                                     EmptyRunnable.getInstance()));
    }
  }

  @Override
  public void reset() {
    myAutoGenerateClosingTagCheckBox.setSelected(HbConfig.isAutoGenerateCloseTagEnabled());
    myAutocompleteMustaches.setSelected(HbConfig.isAutocompleteMustachesEnabled());
    myFormattingCheckBox.setSelected(HbConfig.isFormattingEnabled());
    htmlAsHb.setSelected(HbConfig.shouldOpenHtmlAsHandlebars(myProject));
    resetCommentLanguageCombo(HbConfig.getCommenterLanguage());
  }

  private void resetCommentLanguageCombo(@NotNull Language commentLanguage) {
    final DefaultComboBoxModel<Language> model = (DefaultComboBoxModel<Language>)myCommenterLanguage.getModel();
    final List<Language> languages = ContainerUtil.sorted(ContainerUtil.append(TemplateDataLanguageMappings.getTemplateableLanguages(),
      // add using the native Handlebars commenter as an option
                                                                               HbLanguage.INSTANCE), Comparator.comparing(Language::getID));

    for (Language language : languages) {
      model.addElement(language);
    }

    myCommenterLanguage.setRenderer(LcrJavaHelper.create(
      "",
      value -> {
        FileType type = value.getAssociatedFileType();
        return new RendererPresentation(type != null ? type.getIcon() : null, value.getDisplayName());
      }
    ));
    myCommenterLanguage.setSelectedItem(commentLanguage);
  }
}
