package com.intellij.lang.javascript.validation.fixes;

import com.intellij.ide.util.PlatformPackageUtil;
import com.intellij.javascript.flex.refactoring.FlexRefactoringUtil;
import com.intellij.lang.LanguageNamesValidation;
import com.intellij.lang.javascript.JavascriptLanguage;
import com.intellij.lang.javascript.flex.FlexBundle;
import com.intellij.lang.javascript.refactoring.ui.JSReferenceEditor;
import com.intellij.lang.javascript.ui.ActionScriptPackageChooserDialog;
import com.intellij.lang.refactoring.NamesValidator;
import com.intellij.openapi.module.Module;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.psi.PsiDirectory;
import com.intellij.psi.PsiFile;
import com.intellij.psi.search.GlobalSearchScope;
import com.intellij.refactoring.RefactoringBundle;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.ThreeState;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.Dimension;
import java.awt.Insets;

public class ChoosePackageDialog extends DialogWrapper {
  private static final String DESTINATION_PACKAGE_RECENT_KEY = "ChoosePackageDialog.DESTINATION_PACKAGE_RECENT_KEY";

  private final JPanel myMainPanel;
  private final JSReferenceEditor myPackageCombo;

  private final Module myModule;
  private final String myPackageNameInitial;
  private final PsiFile myContextFile;
  private PsiDirectory myTargetDirectory;

  protected ChoosePackageDialog(final Module module, final String title, final String packageNameInitial, final PsiFile contextFile) {
    super(module.getProject());
    myModule = module;
    myPackageNameInitial = packageNameInitial;
    myContextFile = contextFile;
    {
      myPackageCombo = ActionScriptPackageChooserDialog.createPackageReferenceEditor(myPackageNameInitial, myModule.getProject(),
                                                                                     DESTINATION_PACKAGE_RECENT_KEY,
                                                                                     getPackageScope(), RefactoringBundle.message(
          "choose.destination.package"));
    }
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
      final JLabel label1 = new JLabel();
      label1.setText("Target package:");
      label1.setDisplayedMnemonic('P');
      label1.setDisplayedMnemonicIndex(7);
      myMainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                  false));
      myMainPanel.add(myPackageCombo, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                          GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                          new Dimension(250, -1), null, null, 0, false));
      final Spacer spacer1 = new Spacer();
      myMainPanel.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }
    setTitle(title);
    init();
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  @Override
  public JComponent getPreferredFocusedComponent() {
    return myPackageCombo.getChildComponent();
  }

  @Override
  protected JComponent createCenterPanel() {
    return myMainPanel;
  }

  @Override
  protected void doOKAction() {
    final NamesValidator namesValidator = LanguageNamesValidation.INSTANCE.forLanguage(JavascriptLanguage.INSTANCE);
    final String packageName = getPackageName();
    for (final String s : StringUtil.split(packageName, ".")) {
      if (!namesValidator.isIdentifier(s, null)) {
        setErrorText(FlexBundle.message("invalid.package", packageName), myPackageCombo);
        return;
      }
    }
    myPackageCombo.updateRecents();

    myTargetDirectory = FlexRefactoringUtil.chooseOrCreateDirectoryForClass(myModule.getProject(), myModule, getPackageScope(), packageName,
                                                                            null, myContextFile.getParent(), ThreeState.UNSURE);
    if (myTargetDirectory != null) {
      super.doOKAction();
    }
  }

  private GlobalSearchScope getPackageScope() {
    return PlatformPackageUtil.adjustScope(myContextFile.getParent(), GlobalSearchScope.moduleWithDependenciesScope(myModule), false, true);
  }

  public String getPackageName() {
    return myPackageCombo.getText().trim();
  }

  public PsiDirectory getTargetDirectory() {
    return myTargetDirectory;
  }
}
