image: atlassian/default-image:4

pipelines:
  branches:
    another:
      - step:
          name: Another
          script:
            - echo "A"
    main:
      - step:
          name: Qodana
          caches:
            - qodana
          image: jetbrains/qodana-<linter>
          script:
            - export QODANA_TOKEN=$QODANA_TOKEN  # Export the environment variable
            - qodana --results-dir=$BITBUCKET_CLONE_DIR/.qodana --report-dir=$BITBUCKET_CLONE_DIR/.qodana/report --cache-dir=~/.qodana/cache
          artifacts:
            - .qodana/report
definitions:
  caches:
    qodana: ~/.qodana/cache