package com.intellij.flex.uiDesigner.css {
internal final class StyleManagerPredefinedData {
  public static const colorNames:Object = {
    transparent: "transparent",
    black: 0x000000,
    blue: 0x0000FF,
    green: 0x008000,
    gray: 0x808080,
    silver: 0xC0C0C0,
    lime: 0x00FF00,
    olive: 0x808000,
    white: 0xFFFFFF,
    yellow: 0xFFFF00,
    maroon: 0x800000,
    navy: 0x000080,
    red: 0xFF0000,
    purple: 0x800080,
    teal: 0x008080,
    fuchsia: 0xFF00FF,
    aqua: 0x00FFFF,
    magenta: 0xFF00FF,
    cyan: 0x00FFFF,

    halogreen: 0x80FF4D,
    haloblue: 0x009DFF,
    haloorange: 0xFFB600,
    halosilver: 0xAECAD9
  };

  public static const parentDisplayListOrSizeInvalidatingStyles:Object = {
    baseline: true,
    bottom: true,
    horizontalCenter: true,
    left: true,
    right: true,
    top: true,
    verticalCenter: true
  };

  public static const sizeInvalidatingStyles:Object = {
    alignmentBaseline: true,
    baselineShift: true,
    blockProgression: true,
    borderStyle: true,
    borderThickness: true,
    breakOpportunity : true,
    cffHinting: true,
    columnCount: true,
    columnGap: true,
    columnWidth: true,
    digitCase: true,
    digitWidth: true,
    direction: true,
    dominantBaseline: true,
    firstBaselineOffset: true,
    fontAntiAliasType: true,
    fontFamily: true,
    fontGridFitType: true,
    fontLookup: true,
    fontSharpness: true,
    fontSize: true,
    fontStyle: true,
    fontThickness: true,
    fontWeight: true,
    headerHeight: true,
    horizontalAlign: true,
    horizontalGap: true,
    justificationRule: true,
    justificationStyle: true,
    kerning: true,
    leading: true,
    leadingModel: true,
    letterSpacing: true,
    ligatureLevel: true,
    lineBreak: true,
    lineHeight: true,
    lineThrough: true,
    locale: true,
    marginBottom: true,
    marginLeft: true,
    marginRight: true,
    marginTop: true,
    paddingBottom: true,
    paddingLeft: true,
    paddingRight: true,
    paddingTop: true,
    paragraphEndIndent: true,
    paragraphStartIndent: true,
    paragraphSpaceAfter: true,
    paragraphSpaceBefore: true,
    renderingMode: true,
    strokeWidth: true,
    tabHeight: true,
    tabWidth: true,
    tabStops: true,
    textAlign: true,
    textAlignLast: true,
    textDecoration: true,
    textIndent: true,
    textJustify: true,
    textRotation: true,
    tracking: true,
    trackingLeft: true,
    trackingRight: true,
    typographicCase: true,
    verticalAlign: true,
    verticalGap: true,
    whitespaceCollapse: true
  };

  public static const inheritingTextFormatStyles:Object = {
    align: true,
    bold: true,
    color: true,
    font: true,
    indent: true,
    italic: true,
    size: true
  };
}
}
