CREATE TABLE autogenerated_author (
  author_id INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE autogenerated_book (
  book_id INTEGER NOT NULL PRIMARY KEY,
  year INT,
  title VARCHAR(255) NOT NULL
);

CREATE TABLE autogenerated_author_book (
  book_id INTEGER NOT NULL,
  author_id INTEGER NOT NULL,
  FOREIGN KEY (book_id) REFERENCES autogenerated_book(book_id),
  FOREIGN KEY (author_id) REFERENCES autogenerated_author(author_id)
);